image: microsoft/dotnet-framework

variables:
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe'
  PROPERTIES: /p:OutDir="../output";Configuration=Release;GitHash=$CI_COMMIT_SHORT_SHA;CiBuildNumber=$CI_PIPELINE_IID
  
stages:
  - build

build_job:
  stage: build
  script:
    - '& nuget restore' # restore Nuget dependencies
    - '& "$env:MSBUILD_PATH" SerialKiller.sln "$env:PROPERTIES"' # build the project
  artifacts:
    expire_in: 1 week # save gitlab server space, we copy the files we need to deploy folder later on
    untracked: true
#    paths:
#      - 'output'
