image: microsoft/dotnet:latest


stages:
  - build

build:
    stage: build
    script:
            - cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:Configuration=Release /t:Clean;Build SerialKiller.sln " && exit %%ERRORLEVEL%%
