image: windows:latest


stages:
  - build

build:
    stage: build
    script:
            - C:\Tools\nuget.exe restore
            - cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:Configuration=Release /t:Clean;Build SerialKiller.sln " && exit %%ERRORLEVEL%%
