stages:
  - build-mono

build-mono:
  stage: build-mono
  image: mono:latest
  before_script:
  script:
    - nuget restore SerialKiller.sln
    - msbuild 
        /p:Configuration="Release"
        /p:Platform="Any CPU" 
        "SerialKiller.sln"